#!/usr/bin/env python

import sys
import io
from io import BytesIO
from gtts import gTTS

from pydub import AudioSegment
from pydub.playback import play

audio_file = r'text.mp3'

try:
    input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
    text = input_stream.read()
    print(f'Playing {text}')

    speech = gTTS(text=text, lang='en', slow=False)
    speech.save(audio_file)
    audio = AudioSegment.from_mp3(audio_file)

    # TODO : in memory
        # _fp = BytesIO()
        # speech.write_to_fp(_fp)
        # audio = AudioSegment.from_file(_fp,format='mp3')

    play(audio)



except KeyboardInterrupt:
    sys.stdout.flush()
    pass